version: '3'

services:
  web:
    image: nginx:alpine
    ports:
    - "8084:8080"
    - "443:443"
    volumes:
    - .:/var/www/html/
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./ssl/cert.crt:/etc/nginx/cert.crt
    - ./ssl/cert.key:/etc/nginx/cert.key
    depends_on:
    - php
    - mysql
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "9000:9000"
    volumes:
    - .:/var/www/html/
  mysql:
    image: mysql:5.7
    ports:
    - "3303:3306"
    environment:
      MYSQL_DATABASE: "glpi"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - glpidbdata:/var/lib/mysql

volumes:
  glpidbdata:
