version: '3'

services:
  web:
    image: nginx:alpine
    ports:
    - "8084:8080"
    - "443:443"
    volumes:
    - .:/var/www/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./ssl/cert.crt:/etc/nginx/cert.crt
    - ./ssl/cert.key:/etc/nginx/cert.key
    depends_on:
    - php
    - mysql
  php:
    image: php:7.0-fpm
    ports:
    - "9000:9000"
    volumes:
    - .:/var/www/html
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
    - glpidbdata:/var/lib/mysql

volumes:
  glpidbdata: